apiVersion: v1
kind: ConfigMap
metadata:
  name: kaf-mirror-config
data:
  default.yml: |
    server:
      host: 0.0.0.0
      port: 8080
      mode: production
    source_cluster:
      brokers: "your-source-kafka-brokers"
      security:
        enabled: false
    target_cluster:
      brokers: "your-target-kafka-brokers"
      security:
        enabled: false
