apiVersion: v1
kind: Secret
metadata:
  name: kaf-mirror-secrets
type: Opaque
data:
  # Example secret for a TLS key. The value should be base64 encoded.
  # tls.key: YOUR_BASE64_ENCODED_TLS_KEY
  # Example secret for a token. The value should be base64 encoded.
  # api.token: YOUR_BASE64_ENCODED_API_TOKEN
